In [15]:
import scipy
from scipy.stats import ttest_rel
import numpy as np

In [24]:
#Logistic Regression
lg_acc_array = np.array([0.9222938581608415, 
 0.9226331862911435, 
 0.9226331862911435, 
 0.9226331862911435,
 0.9222938581608415])
lg_f1_array = np.array([0.9222938581608415,
 0.9226331862911435,
 0.9226331862911435,
 0.9226331862911435,
 0.9222938581608415])
lg_pres_array = np.array([0.9226331862911435,
 0.9226331862911435,
 0.9226331862911435,
 0.9226331862911435,
 0.9226331862911435])

lg_mean_scores = np.array([])
for i in np.arange(0,5):
    mean = np.mean([lg_acc_array[i],lg_f1_array[i],lg_pres_array[i]])
    lg_mean_scores = np.append(lg_mean_scores, mean)

lg_mean_scores

array([0.92240697, 0.92263319, 0.92263319, 0.92263319, 0.92240697])

In [25]:
#Decision Trees
dt_acc_array = np.array([0.8242280285035629,
 0.825924669155073,
 0.831014591109603,
 0.831014591109603,
 0.8245673566338649])
dt_f1_array = np.array([
0.825585341024771,
 0.824906684764167,
 0.8310145911096029,
 0.829996606718697,
 0.825585341024771 ])
dt_pres_array = np.array([0.7964031218187988,
 0.7974211062097047,
 0.7974211062097047,
 0.7964031218187988,
 0.7964031218187988])

dt_mean_scores = np.array([])
for i in np.arange(0,5):
    mean = np.mean([dt_acc_array[i],dt_f1_array[i],dt_pres_array[i]])
    dt_mean_scores = np.append(dt_mean_scores, mean)

dt_mean_scores

array([0.8154055 , 0.81608415, 0.81981676, 0.81913811, 0.81551861])

In [26]:
#Knn
knn_acc_array = np.array([0.8853070919579233,
 0.8768238887003733,
 0.8517136070580251,
 0.8873430607397353,
 0.8873430607397353])
knn_f1_array = np.array([0.8853070919579233,
 0.8768238887003733,
 0.8517136070580251,
 0.8873430607397353,
 0.8873430607397353])
knn_pres_array = np.array([0.8853070919579233,
 0.8768238887003733,
 0.8517136070580251,
 0.8873430607397353,
 0.8873430607397353])


knn_mean_scores = np.array([])
for i in np.arange(0,5):
    mean = np.mean([knn_acc_array[i],knn_f1_array[i],knn_pres_array[i]])
    knn_mean_scores = np.append(knn_mean_scores, mean)

knn_mean_scores

array([0.88530709, 0.87682389, 0.85171361, 0.88734306, 0.88734306])

In [27]:
#random forest
rf_acc_array = np.array([0.8971835765184933,
 0.8934509670851714,
 0.8944689514760774,
 0.8998982015609094,
 0.8954869358669834])
rf_f1_array = np.array([0.8934509670851712,
 0.8927723108245673,
 0.9012555140821175,
 0.8907363420427553,
 0.8992195453003053])
rf_pres_array = np.array([0.9022734984730234,
 0.8941296233457754,
 0.9043094672548354,
 0.8924329826942654,
 0.8927723108245673])

rf_mean_scores = np.array([])
for i in np.arange(0,5):
    mean = np.mean([rf_acc_array[i],rf_f1_array[i],rf_pres_array[i]])
    rf_mean_scores = np.append(rf_mean_scores, mean)

rf_mean_scores

array([0.89763601, 0.89345097, 0.90001131, 0.89435584, 0.89582626])

In [28]:
#SVM
svm_acc_array = np.array([0.9450288428910757,
 0.9450288428910757,
 0.9470648116728877,
 0.9450288428910757,
 0.9450288428910757])
svm_f1_array = np.array([0.9450288428910757,
 0.9450288428910757,
 0.9470648116728877,
 0.9450288428910757,
 0.9450288428910757])
svm_pres_array = np.array([0.9450288428910757,
 0.9450288428910757,
 0.9470648116728877,
 0.9450288428910757,
 0.9450288428910757])

svm_mean_scores = np.array([])
for i in np.arange(0,5):
    mean = np.mean([svm_acc_array[i],svm_f1_array[i],svm_pres_array[i]])
    svm_mean_scores = np.append(svm_mean_scores, mean)

svm_mean_scores

array([0.94502884, 0.94502884, 0.94706481, 0.94502884, 0.94502884])

In [31]:
#XGBoost
xgb_acc_array = np.array([0.8998982015609094,
 0.9015948422124194,
 0.9043094672548354,
 0.8968442483881914,
 0.9009161859518154])
xgb_f1_array = np.array([0.8998982015609094,
 0.9015948422124194,
 0.9043094672548354,
 0.8968442483881914,
 0.9009161859518154])
xgb_pres_array = np.array([0.8998982015609094,
 0.9015948422124194,
 0.9043094672548354,
 0.8968442483881914,
 0.9009161859518154])

xgb_mean_scores = np.array([])
for i in np.arange(0,5):
    mean = np.mean([xgb_acc_array[i],xgb_f1_array[i],xgb_pres_array[i]])
    xgb_mean_scores = np.append(xgb_mean_scores, mean)

xgb_mean_scores

array([0.8998982 , 0.90159484, 0.90430947, 0.89684425, 0.90091619])

In [ ]:
#ann
ann_acc_array = np.array([
ann_f1_array = np.array([
ann_pres_array = np.array([
ann_mean_scores = np.mean([ann_acc_array,ann_f1_array,ann_pres_array])
ann_mean_scores

In [37]:
#logistic regression vs Decision Trees
scipy.stats.ttest_rel(lg_mean_scores, dt_mean_scores)

Ttest_relResult(statistic=116.37046412379647, pvalue=3.270140520202308e-08)

In [38]:
#logistic regression vs knn
scipy.stats.ttest_rel(lg_mean_scores, knn_mean_scores)

Ttest_relResult(statistic=6.583064801426907, pvalue=0.002756876014444544)

In [39]:
#logistic regression vs random forest
scipy.stats.ttest_rel(lg_mean_scores, rf_mean_scores)

Ttest_relResult(statistic=22.152429825922653, pvalue=2.458038705451503e-05)

In [40]:
#logistic regression vs SVM
scipy.stats.ttest_rel(lg_mean_scores, svm_mean_scores)

Ttest_relResult(statistic=-59.02103856420462, pvalue=4.935068307902863e-07)

In [41]:
#logistic regression vs XGBoost
scipy.stats.ttest_rel(lg_mean_scores, xgb_mean_scores)

Ttest_relResult(statistic=18.076106163526774, pvalue=5.5070912349657567e-05)